### ISSUE TITLE
style update

### ISSUE THREAD

**Issue by greschd** [FrescolinoGroup/FrescolinoGroup.github.io#3]
I think we should start collecting ideas for how the style of the website can be improved. Implementing it is low priority, but when we come around to doing it we'll know what to do.

**Comment by greschd** [comment]
I think the tiles should be fixed size, because not having them aligned looks ugly imo
![screenshot from 2016-09-15 11-47-37](https://cloud.githubusercontent.com/assets/5692808/18545699/87dfe81c-7b3a-11e6-82c2-19af86d6c343.png)
same goes for the parts within each tile (align title, description, etc.)

**Comment by mskoenz** [comment]
- made all modules same width
- alligned titles, descr and versions vertically

![for_now](https://cloud.githubusercontent.com/assets/1257706/18626398/2ff9d7fc-7e55-11e6-9b36-40bac9b2aaed.png)

**Comment by mskoenz** [comment]
lets keep the issue open for further ideas...

**Comment by mskoenz** [comment]
nvm, post all further style proposals here: #1
